name: disposal
version: 0.1.0-alpha.5
description: Disposable interfaces used for managing resource disposal.
homepage: https://github.com/LoveCommunity/disposal.dart

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies: 
  meta: ^1.3.0 
  typedef_foundation: ^0.1.0

dev_dependencies:
  test: ^1.17.12
